### ISSUE TITLE
Daemonise gocart

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/gocart#13]

**Comment by genghisken** [comment]
Interesting... Had my test code mostly done and then discovered that for python3 the API has changed. Looking into the required changes now. Hopefully not too onerous.

**Comment by genghisken** [comment]
I've implemented daemonisation for my gkligo map downloader, so applying to gocart should be straightforward. The only caveat is that Consumer.consume() will override kill signals unless we call it with a timeout value.

**Comment by thespacedoctor** [comment]
I think I have this working now. I added a generalised `daemonise` class to my fundamentals package which sets up the daemon and all its assets (pid file, log files etc) and includes all the stop/start/restart/status methods.

<https://fundamentals.readthedocs.io/en/master/_autosummary/fundamentals.daemonise.html#fundamentals.daemonise>

Gocart now uses this class to create the listen daemon.

Thanks for your help @genghisken.

**Comment by genghisken** [comment]
Hurray! Are you using a timeout with Consume()? Mine's been working fine for ages now, but only because I introduced the timeout.

**Comment by thespacedoctor** [comment]
Yes, see here: https://github.com/thespacedoctor/gocart/blob/e54ac4535cffa793f6806795ecb0c7ecf81e27ee/gocart/cl_utils.py#L216

Might increase this to 5 or 10s.
