### ISSUE TITLE
remove ligo.skymap dependency from gocart

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/gocart#24]

**Comment by thespacedoctor** [comment]
The `ligo.skymap` code has a huge number of dependencies and is causing upgrades of `gocart` to take ~20-40 mins as conda resolves out all these dependencies against one another.

**Comment by thespacedoctor** [comment]
Dependency has been removed. I had to rewrite the multi-order map > single-order map code found in `ligo.skymap`. Coded using pandas, and it is producing the same results as `ligo.skymap`.

**Comment by genghisken** [comment]
Nice!
