### ISSUE TITLE
Add a table of metric along the RHS of the aitoff plots

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/gocart#8]
This should include the event name, the alert flavour and other meta from the FITS header and alert.

**Comment by thespacedoctor** [comment]
![image](https://user-images.githubusercontent.com/3385557/229537881-d498b8e4-8dbe-4162-9c63-1daccd9ec80b.png)

Final tweaks:

- [x] make axis labels visible above event map
- [x] make event map transparent to see galactic plane behind
- [x] alert precision of classifications to make them more  readable

**Comment by thespacedoctor** [comment]
![image](https://user-images.githubusercontent.com/3385557/229544624-5db3eb44-d6dc-41f2-83c9-172cbe333db3.png)

Any other comments/requests for these aitoff plots @smarttgit and @mnicholl?

**Comment by smarttgit** [comment]
Looks great @thespacedoctor . 
What about adding the type of map this is  (bayestar or bilby)

**Comment by thespacedoctor** [comment]
Added localisation: 

![image](https://user-images.githubusercontent.com/3385557/230105147-3bc805cb-1646-4455-9afa-8b0a36c79fe2.png)
